### ISSUE TITLE
Kubernetes context info gives error when not set

### ISSUE THREAD

**Issue by TristanWiley** [umayr/theme-sushi#12]
If Kubernetes context info is not set, instead of not showing anything an error is shown every load and after any command.

Screenshot example:
![Screen Shot 2019-07-23 at 3 32 11 PM](https://user-images.githubusercontent.com/2747793/61751991-0f32da00-ad5f-11e9-89cb-c6cbc36842e0.png)

**Comment by umayr** [comment]
Fixed by #14
